# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import prompt_mode_pb2 as prompt__mode__pb2


class OpenAIPromptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompletePrompt = channel.unary_unary(
                '/openai_prompt_service.OpenAIPromptService/CompletePrompt',
                request_serializer=prompt__mode__pb2.OpenAIPromptRequest.SerializeToString,
                response_deserializer=prompt__mode__pb2.OpenAIPromptResponse.FromString,
                )


class OpenAIPromptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompletePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenAIPromptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompletePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.CompletePrompt,
                    request_deserializer=prompt__mode__pb2.OpenAIPromptRequest.FromString,
                    response_serializer=prompt__mode__pb2.OpenAIPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openai_prompt_service.OpenAIPromptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpenAIPromptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompletePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openai_prompt_service.OpenAIPromptService/CompletePrompt',
            prompt__mode__pb2.OpenAIPromptRequest.SerializeToString,
            prompt__mode__pb2.OpenAIPromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
