# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prompt_mode.proto
<<<<<<< HEAD
# Protobuf Python Version: 4.25.1
=======
>>>>>>> 10c5386 (raw)
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
<<<<<<< HEAD

=======
>>>>>>> 10c5386 (raw)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

<<<<<<< HEAD
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11prompt_mode.proto\x12\x13prompt_mode_service\"F\n\x11PromptModeRequest\x12\x0f\n\x07mode_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\x05\"\x17\n\x04\x44\x61ta\x12\x0f\n\x07message\x18\x01 \x01(\t\"q\n\x12PromptModeResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.prompt_mode_service.Data\x12\x11\n\texecution\x18\x04 \x01(\x02\x32q\n\x11PromptModeService\x12\\\n\tGetAnswer\x12&.prompt_mode_service.PromptModeRequest\x1a\'.prompt_mode_service.PromptModeResponseb\x06proto3')
=======



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11prompt_mode.proto\x12\x13prompt_mode_service\"F\n\x11PromptModeRequest\x12\x0f\n\x07mode_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\x05\"\x17\n\x04\x44\x61ta\x12\x0f\n\x07message\x18\x01 \x01(\t\"q\n\x12PromptModeResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.prompt_mode_service.Data\x12\x11\n\texecution\x18\x04 \x01(\x02\x32q\n\x11PromptModeService\x12\\\n\tGetAnswer\x12&.prompt_mode_service.PromptModeRequest\x1a\'.prompt_mode_service.PromptModeResponseb\x06proto3')
>>>>>>> 10c5386 (raw)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prompt_mode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
<<<<<<< HEAD
    DESCRIPTOR._options = None
    _globals['_PROMPTMODEREQUEST']._serialized_start = 42
    _globals['_PROMPTMODEREQUEST']._serialized_end = 112
    _globals['_DATA']._serialized_start = 114
    _globals['_DATA']._serialized_end = 137
    _globals['_PROMPTMODERESPONSE']._serialized_start = 139
    _globals['_PROMPTMODERESPONSE']._serialized_end = 252
    _globals['_PROMPTMODESERVICE']._serialized_start = 254
    _globals['_PROMPTMODESERVICE']._serialized_end = 367
=======
  DESCRIPTOR._options = None
  _globals['_PROMPTMODEREQUEST']._serialized_start=42
  _globals['_PROMPTMODEREQUEST']._serialized_end=112
  _globals['_DATA']._serialized_start=114
  _globals['_DATA']._serialized_end=137
  _globals['_PROMPTMODERESPONSE']._serialized_start=139
  _globals['_PROMPTMODERESPONSE']._serialized_end=252
  _globals['_PROMPTMODESERVICE']._serialized_start=254
  _globals['_PROMPTMODESERVICE']._serialized_end=367
>>>>>>> 10c5386 (raw)
# @@protoc_insertion_point(module_scope)
