version: '3'

services:
  amocrm_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_amocrm_connect
    ports:
      - "50051:50051"

  openai_prompt_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_prompt_mode
    ports:
      - "50052:50052"

  openai_whisper_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_whisper
    ports:
      - "50053:50053"

  qualification_mode_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_qualification
    ports:
      - "50054:50054"

  amocrm_service_site:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_amocrm_site
    ports:
      - "50060:50060"
