version: '3'

services:
  core_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile

  core_bitrix_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_bitrix
