version: '3'

services:
  amocrm_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_amocrm_connect
    ports:
      - "50051:50051"

  core_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile
