version: '3'

services:
  amocrm_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_amocrm_connect
    ports:
      - "50051:50051"

  openai_prompt_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_prompt_mode
    ports:
      - "50052:50052"

  openai_whisper_service:
    build:
      context: .
      dockerfile: common/docker/Dockerfile_whisper
    ports:
      - "50053:50053"
