version: '3'

services:
  openai_prompt_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_prompt_mode
    ports:
      - "50052:50052"

  openai_whisper_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_whisper
    ports:
      - "50053:50053"

  qualification_mode_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_qualification
    ports:
      - "50054:50054"

  knowledge_mode_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_knowledge
    ports:
      - "50055:50055"

  gpts_mode_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_assistants
    ports:
      - "50056:50056"

  search_mode_service:
    restart: always
    build:
      context: .
      dockerfile: common/docker/Dockerfile_search_mode
    ports:
      - "50057:50057"

