# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whisper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rwhisper.proto\x12\x07whisper"4\n\rWisperRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x16\n\x0eopenai_api_key\x18\x02 \x01(\t" \n\x0eWisperResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2P\n\x0eWhisperService\x12>\n\x0bVoiceToText\x12\x16.whisper.WisperRequest\x1a\x17.whisper.WisperResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "whisper_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_WISPERREQUEST"]._serialized_start = 26
    _globals["_WISPERREQUEST"]._serialized_end = 78
    _globals["_WISPERRESPONSE"]._serialized_start = 80
    _globals["_WISPERRESPONSE"]._serialized_end = 112
    _globals["_WHISPERSERVICE"]._serialized_start = 114
    _globals["_WHISPERSERVICE"]._serialized_end = 194
# @@protoc_insertion_point(module_scope)
