# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import whisper_pb2 as whisper__pb2


class WhisperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoiceToText = channel.unary_unary(
            "/whisper.WhisperService/VoiceToText",
            request_serializer=whisper__pb2.WisperRequest.SerializeToString,
            response_deserializer=whisper__pb2.WisperResponse.FromString,
        )


class WhisperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoiceToText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WhisperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "VoiceToText": grpc.unary_unary_rpc_method_handler(
            servicer.VoiceToText,
            request_deserializer=whisper__pb2.WisperRequest.FromString,
            response_serializer=whisper__pb2.WisperResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "whisper.WhisperService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class WhisperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoiceToText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper.WhisperService/VoiceToText",
            whisper__pb2.WisperRequest.SerializeToString,
            whisper__pb2.WisperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
