# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13qualification.proto\x12\x15qualification_service\"1\n\x06Select\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04sort\x18\x03 \x01(\x05\"}\n\x05\x46ield\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63tive_value\x18\x04 \x01(\t\x12\x36\n\x0fpossible_values\x18\x05 \x03(\x0b\x32\x1d.qualification_service.Select\"\x84\x01\n\rAvatarexField\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x36\n\x0fpossible_values\x18\x05 \x03(\x0b\x32\x1d.qualification_service.Select\"\xb9\x01\n\x14QualificationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x33\n\rfields_amocrm\x18\x03 \x03(\x0b\x32\x1c.qualification_service.Field\x12=\n\x0f\x66ields_avatarex\x18\x04 \x03(\x0b\x32$.qualification_service.AvatarexField\x12\x0e\n\x06\x66inish\x18\x05 \x01(\t\".\n\x0cResponseData\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"s\n\x15QualificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x31\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32#.qualification_service.ResponseData\x12\x16\n\x0e\x65xecution_time\x18\x03 \x01(\x02\x32\x8b\x01\n\x14QualificationService\x12s\n\x14\x45xecuteQualification\x12+.qualification_service.QualificationRequest\x1a,.qualification_service.QualificationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELECT']._serialized_start=46
  _globals['_SELECT']._serialized_end=95
  _globals['_FIELD']._serialized_start=97
  _globals['_FIELD']._serialized_end=222
  _globals['_AVATAREXFIELD']._serialized_start=225
  _globals['_AVATAREXFIELD']._serialized_end=357
  _globals['_QUALIFICATIONREQUEST']._serialized_start=360
  _globals['_QUALIFICATIONREQUEST']._serialized_end=545
  _globals['_RESPONSEDATA']._serialized_start=547
  _globals['_RESPONSEDATA']._serialized_end=593
  _globals['_QUALIFICATIONRESPONSE']._serialized_start=595
  _globals['_QUALIFICATIONRESPONSE']._serialized_end=710
  _globals['_QUALIFICATIONSERVICE']._serialized_start=713
  _globals['_QUALIFICATIONSERVICE']._serialized_end=852
# @@protoc_insertion_point(module_scope)
