# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import knowledge_mode_pb2 as knowledge__mode__pb2


class OpenAIKnowledgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompleteKnowledge = channel.unary_unary(
                '/openai_knowledge_service.OpenAIKnowledgeService/CompleteKnowledge',
                request_serializer=knowledge__mode__pb2.OpenAIKnowledgeRequest.SerializeToString,
                response_deserializer=knowledge__mode__pb2.OpenAIKnowledgeResponse.FromString,
                )


class OpenAIKnowledgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompleteKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenAIKnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompleteKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteKnowledge,
                    request_deserializer=knowledge__mode__pb2.OpenAIKnowledgeRequest.FromString,
                    response_serializer=knowledge__mode__pb2.OpenAIKnowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openai_knowledge_service.OpenAIKnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpenAIKnowledgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompleteKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openai_knowledge_service.OpenAIKnowledgeService/CompleteKnowledge',
            knowledge__mode__pb2.OpenAIKnowledgeRequest.SerializeToString,
            knowledge__mode__pb2.OpenAIKnowledgeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
